spring:
  application:
    name: man-sedan

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    